name: Validate with hassfest

# Removed push not to duplicate
on:
  workflow_dispatch:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  hassfest_custom:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      - uses: home-assistant/actions/hassfest@f4ca6f671bd429efb108c0f2fa0ae8af0215986c
